(function(){
var root=document.getElementById('memory-camera-app');if(!root||root.dataset.ready==='1')return;root.dataset.ready='1';
var q=function(s){return root.querySelector(s)},canvas=q('#mc-canvas'),ctx=canvas.getContext('2d'),drop=q('#mc-drop'),file=q('#mc-file');
var state={lang:'zh',style:'phone',orientation:'landscape',color:'white',size:720,img:null,playing:false};
var words={
zh:{title:'把一张照片，变成一段记忆',subtitle:'模拟取景、对焦与快门，导出属于你的短 GIF。',drop:'拖入、粘贴或选择一张图片',formats:'支持 JPG、PNG、WebP',choose:'选择图片',privacy:'图片仅在你的浏览器中处理，不会上传到服务器。',style:'取景风格',phone:'手机',camera:'相机',film:'胶片',orientation:'画面方向',landscape:'横向',portrait:'纵向',caption:'记忆文字',captionPlaceholder:'写下此刻想记住的话……',white:'白色',yellow:'黄色',italic:'斜体文字',quality:'导出尺寸',small:'小',medium:'中',large:'大',loop:'循环播放 GIF',play:'播放记忆',replay:'重新播放',png:'保存 PNG',gif:'导出 GIF',encoding:'正在制作 GIF…',done:'已保存',bad:'请选择有效的图片',loading:'正在读取图片…'},
en:{title:'Turn a photo into a memory',subtitle:'A viewfinder, a moment of focus, and a shutter—saved as a short GIF.',drop:'Drop, paste, or choose an image',formats:'JPG, PNG, and WebP supported',choose:'Choose image',privacy:'Your image is processed only in this browser and is never uploaded.',style:'Viewfinder style',phone:'Phone',camera:'Camera',film:'Film',orientation:'Orientation',landscape:'Landscape',portrait:'Portrait',caption:'Memory caption',captionPlaceholder:'Write something worth remembering…',white:'White',yellow:'Yellow',italic:'Italic text',quality:'Export size',small:'Small',medium:'Medium',large:'Large',loop:'Loop the GIF',play:'Play memory',replay:'Replay',png:'Save PNG',gif:'Export GIF',encoding:'Creating GIF…',done:'Saved',bad:'Please choose a valid image',loading:'Loading image…'},
ja:{title:'一枚の写真を、ひとつの記憶へ',subtitle:'ファインダー、ピント、シャッターの瞬間を短いGIFに。',drop:'画像をドロップ・貼り付け・選択',formats:'JPG・PNG・WebP に対応',choose:'画像を選ぶ',privacy:'画像はブラウザ内だけで処理され、サーバーには送信されません。',style:'ファインダー',phone:'スマホ',camera:'カメラ',film:'フィルム',orientation:'向き',landscape:'横',portrait:'縦',caption:'記憶の言葉',captionPlaceholder:'この瞬間に残したい言葉…',white:'白',yellow:'黄',italic:'斜体',quality:'出力サイズ',small:'小',medium:'中',large:'大',loop:'GIFをループ',play:'記憶を再生',replay:'もう一度',png:'PNGを保存',gif:'GIFを書き出す',encoding:'GIFを作成中…',done:'保存しました',bad:'有効な画像を選んでください',loading:'画像を読み込み中…'}};
var modeWords={zh:{photo:'照片',video:'视频',portrait:'人像',pano:'全景',slowmo:'慢动作',live:'实况'},en:{photo:'PHOTO',video:'VIDEO',portrait:'PORTRAIT',pano:'PANO',slowmo:'SLO-MO',live:'LIVE'},ja:{photo:'写真',video:'ビデオ',portrait:'ポートレート',pano:'パノラマ',slowmo:'スロー',live:'LIVE'}};
var extraWords={zh:{shootEffect:'拍摄效果',parameters:'取景参数',flash:'闪光灯',auto:'自动',on:'开启',off:'关闭',zoom:'倍率',time:'时间',aperture:'光圈',shutter:'快门',tone:'色调',warm:'暖色',neutral:'自然',cool:'冷色',grain:'颗粒',low:'低',high:'高',dateStamp:'日期戳',font:'字体',fontSans:'无衬线',fontSerif:'衬线',fontHand:'手写',fontMono:'等宽',position:'位置',bottom:'底部',center:'中央',top:'顶部',black:'黑色',pink:'粉色',blue:'蓝色',customColor:'自定义颜色',fontSize:'字号',bold:'粗体',stroke:'描边',imageAdjust:'图片调整',imageScale:'缩放',imageX:'水平',imageY:'垂直'},en:{shootEffect:'Capture effect',parameters:'Viewfinder settings',flash:'Flash',auto:'Auto',on:'On',off:'Off',zoom:'Zoom',time:'Time',aperture:'Aperture',shutter:'Shutter',tone:'Tone',warm:'Warm',neutral:'Natural',cool:'Cool',grain:'Grain',low:'Low',high:'High',dateStamp:'Date stamp',font:'Font',fontSans:'Sans serif',fontSerif:'Serif',fontHand:'Handwriting',fontMono:'Monospace',position:'Position',bottom:'Bottom',center:'Center',top:'Top',black:'Black',pink:'Pink',blue:'Blue',customColor:'Custom color',fontSize:'Size',bold:'Bold',stroke:'Outline',imageAdjust:'Image adjustment',imageScale:'Scale',imageX:'Horizontal',imageY:'Vertical'},ja:{shootEffect:'撮影エフェクト',parameters:'撮影設定',flash:'フラッシュ',auto:'自動',on:'オン',off:'オフ',zoom:'倍率',time:'時刻',aperture:'絞り',shutter:'シャッター',tone:'色調',warm:'暖色',neutral:'自然',cool:'寒色',grain:'粒子',low:'弱',high:'強',dateStamp:'日付スタンプ',font:'フォント',fontSans:'ゴシック',fontSerif:'明朝',fontHand:'手書き',fontMono:'等幅',position:'位置',bottom:'下',center:'中央',top:'上',black:'黒',pink:'ピンク',blue:'青',customColor:'カスタム色',fontSize:'文字サイズ',bold:'太字',stroke:'縁取り',imageAdjust:'画像調整',imageScale:'拡大',imageX:'水平',imageY:'垂直'}};
function t(k){return words[state.lang][k]||extraWords[state.lang][k]||k}function mt(k){return modeWords[state.lang][k]||k}
function translate(){root.querySelectorAll('[data-i18n]').forEach(function(el){el.textContent=t(el.dataset.i18n)});root.querySelectorAll('[data-placeholder]').forEach(function(el){el.placeholder=t(el.dataset.placeholder)});root.querySelectorAll('[data-i18n-title]').forEach(function(el){el.title=t(el.dataset.i18nTitle)});if(state.img)q('#mc-play').textContent=t('replay')}
function choose(group,key){root.querySelectorAll(group+' button').forEach(function(b){b.addEventListener('click',function(){root.querySelectorAll(group+' button').forEach(function(x){x.classList.remove('active')});b.classList.add('active');state[key]=b.dataset.value;if(key==='size')state[key]=+state[key];if(key==='style')updateParamPanel();if(state.img)draw(1,0)})})}
function updateParamPanel(){root.querySelectorAll('.mc-param-panel').forEach(function(p){p.hidden=p.dataset.panel!==state.style})}
function flashMark(){var v=q('#mc-phone-flash').value;return v==='auto'?'⚡A':v==='on'?'⚡':'⚡̸'}function zoomValue(){return q('#mc-phone-zoom').value}
root.querySelectorAll('[data-lang]').forEach(function(b){b.addEventListener('click',function(){root.querySelectorAll('[data-lang]').forEach(function(x){x.classList.remove('active')});b.classList.add('active');state.lang=b.dataset.lang;translate();if(state.img)draw(1,0)})});choose('#mc-styles','style');choose('#mc-orientation','orientation');choose('#mc-colors','color');choose('#mc-sizes','size');
function dims(){if(state.style==='phone')return state.orientation==='portrait'?{w:Math.round(state.size*.5625),h:state.size}:{w:state.size,h:Math.round(state.size*.5625)};return state.orientation==='portrait'?{w:Math.round(state.size*.72),h:state.size}:{w:state.size,h:Math.round(state.size*.625)}}
function setup(){var d=dims();canvas.width=d.w;canvas.height=d.h;canvas.style.display='block';drop.style.display='none'}
function viewRect(){var w=canvas.width,h=canvas.height;if(state.style==='phone'){if(state.orientation==='portrait')return{x:0,y:Math.round(h*.072),w:w,h:Math.round(h*.72)};return{x:Math.round(w*.072),y:0,w:Math.round(w*.72),h:h}}if(state.style==='camera')return{x:Math.round(w*.025),y:Math.round(h*.075),w:Math.round(w*.95),h:Math.round(h*.79)};return{x:0,y:0,w:w,h:h}}
function cover(img,zoom,pan,r){var userZoom=+q('#mc-image-scale').value/100,s=Math.max(r.w/img.width,r.h/img.height)*zoom*userZoom,sw=r.w/s,sh=r.h/s,maxX=Math.max(0,img.width-sw),maxY=Math.max(0,img.height-sh),px=+q('#mc-image-x').value/100,py=+q('#mc-image-y').value/100,sx=maxX*(px+1)/2+pan*img.width*.018,sy=maxY*(py+1)/2;sx=Math.max(0,Math.min(maxX,sx));sy=Math.max(0,Math.min(maxY,sy));ctx.drawImage(img,sx,sy,sw,sh,r.x,r.y,r.w,r.h)}
function caption(){var text=q('#mc-caption').value.trim();if(!text)return;var w=canvas.width,h=canvas.height,size=Math.max(12,+q('#mc-font-size').value*w/720),families={sans:'Arial,"Noto Sans SC","Noto Sans JP",sans-serif',serif:'Georgia,"Noto Serif SC","Noto Serif JP",serif',hand:'"Segoe Print","Klee One",KaiTi,cursive',mono:'Consolas,"Noto Sans Mono",monospace'},colors={white:'#fff',black:'#111',yellow:'#ffe56d',pink:'#ff82ad',blue:'#73baff'},color=state.color==='custom'?q('#mc-custom-color').value:(colors[state.color]||'#fff'),italic=q('#mc-italic').checked?'italic ':'',weight=q('#mc-bold').checked?'700 ':'400 ';ctx.save();ctx.font=italic+weight+size+'px '+families[q('#mc-font').value];ctx.textAlign='center';ctx.textBaseline='bottom';ctx.lineWidth=Math.max(2,size*.16);ctx.strokeStyle=(color==='#111')?'rgba(255,255,255,.7)':'rgba(0,0,0,.65)';ctx.fillStyle=color;var limit=Math.max(8,Math.floor(w/size*1.5)),lines=text.match(new RegExp('.{1,'+limit+'}','g'))||[text],lh=size*1.25,target=h*(+q('#mc-caption-y').value/100),minY=size*1.2,maxY=h-size*.45-(lines.length-1)*lh,y=Math.max(minY,Math.min(maxY,target-(lines.length-1)*lh/2));for(var i=0;i<lines.length;i++){if(q('#mc-stroke').checked)ctx.strokeText(lines[i],w/2,y+i*lh);ctx.fillText(lines[i],w/2,y+i*lh)}ctx.restore()}
function overlay(progress){var w=canvas.width,h=canvas.height,u=w/720,portrait=state.orientation==='portrait';ctx.save();ctx.lineWidth=Math.max(1,1.5*u);ctx.textBaseline='middle';if(state.style==='phone'){portrait?phonePortraitUI(w,h,progress):phoneLandscapeUI(w,h,progress)}else if(state.style==='camera'){portrait?cameraPortraitUI(w,h,u,progress):cameraLandscapeUI(w,h,u,progress)}else{portrait?filmPortraitUI(w,h,u):filmLandscapeUI(w,h,u)}ctx.restore();caption();if(q('#mc-shoot').checked)captureEffect(progress,w,h,u)}
function phoneStatus(w,y,s,inset){var left=inset||18*s,right=w-(inset||18*s);ctx.fillStyle='#fff';ctx.font='600 '+(12*s)+'px -apple-system,Arial';ctx.textAlign='left';ctx.fillText(q('#mc-phone-time').value||'9:41',left,y);var x=right-56*s,bottom=y+5*s;for(var i=0;i<4;i++){var bh=(4+i*2)*s;ctx.fillRect(x+i*4*s,bottom-bh,2.5*s,bh)}x=right-31*s;ctx.strokeStyle='#fff';ctx.lineWidth=1.55*s;ctx.beginPath();ctx.arc(x,y+6*s,10*s,Math.PI*1.2,Math.PI*1.8);ctx.stroke();ctx.beginPath();ctx.arc(x,y+6*s,6.5*s,Math.PI*1.2,Math.PI*1.8);ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(x,y+3.5*s,1.6*s,0,Math.PI*2);ctx.fill();x=right-17*s;ctx.lineWidth=1.4*s;ctx.strokeRect(x,y-5*s,15*s,10*s);ctx.fillRect(x+2*s,y-3*s,10*s,6*s);ctx.fillRect(x+15*s,y-2*s,2*s,4*s)}
function switchIcon(x,y,s){ctx.save();ctx.translate(x,y);ctx.strokeStyle='#fff';ctx.lineWidth=1.8*s;ctx.beginPath();ctx.arc(0,0,9*s,-Math.PI*.15,Math.PI*.75);ctx.stroke();ctx.beginPath();ctx.moveTo(7*s,-6*s);ctx.lineTo(10*s,-7*s);ctx.lineTo(9*s,-3*s);ctx.stroke();ctx.beginPath();ctx.arc(0,0,9*s,Math.PI*.85,Math.PI*1.75);ctx.stroke();ctx.beginPath();ctx.moveTo(-7*s,6*s);ctx.lineTo(-10*s,7*s);ctx.lineTo(-9*s,3*s);ctx.stroke();ctx.strokeRect(-4*s,-3*s,8*s,6*s);ctx.restore()}
function phonePortraitUI(w,h,p,rotated){var r=rotated?{x:0,y:Math.round(h*.072),w:w,h:Math.round(h*.72)}:viewRect(),s=w/405;phoneStatus(w,20*s,s,18*s);ctx.fillStyle='#fff';ctx.font=(12*s)+'px Arial';ctx.textAlign='left';ctx.fillText(flashMark(),20*s,r.y-9*s);ctx.textAlign='center';ctx.fillText('⌃',w/2,r.y-9*s);ctx.textAlign='right';ctx.fillText('◎',w-20*s,r.y-9*s);ctx.textAlign='center';var zy=r.y+r.h+14*s;['0.5','1','2','3'].forEach(function(z,i){ctx.fillStyle=z===zoomValue()?'#ffd84d':'#fff';ctx.font='700 '+(12*s)+'px Arial';ctx.fillText(z+'×',w/2+(i-1.5)*42*s,zy)});ctx.fillStyle='#ffd84d';ctx.font='700 '+(12*s)+'px Arial';ctx.fillText(mt('photo'),w/2,h-112*s);ctx.fillStyle='#aaa';ctx.font=(11*s)+'px Arial';ctx.fillText(mt('slowmo')+'     '+mt('video')+'             '+mt('portrait')+'     '+mt('pano'),w/2,h-90*s);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(w/2,h-48*s,27*s,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#999';ctx.lineWidth=s;ctx.beginPath();ctx.arc(w/2,h-48*s,31*s,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#333';ctx.fillRect(18*s,h-70*s,44*s,44*s);ctx.strokeStyle='#fff';ctx.strokeRect(21*s,h-67*s,38*s,38*s);switchIcon(w-40*s,h-48*s,s)}
function phoneLandscapeUI(w,h,p){ctx.save();ctx.translate(0,h);ctx.rotate(-Math.PI/2);phonePortraitUI(h,w,p,true);ctx.restore()}
function cameraPoints(r,u,p){if(!q('#mc-shoot').checked||p<.08||p>.72)return;var cx=r.x+r.w/2,cy=r.y+r.h/2,sz=14*u,gx=Math.min(r.w*.105,52*u),gy=Math.min(r.h*.12,42*u);for(var yy=-1;yy<=1;yy++)for(var xx=-2;xx<=2;xx++){ctx.strokeStyle=(xx===0&&yy===0)?'#66f272':'rgba(255,255,255,.55)';ctx.strokeRect(cx+xx*gx-sz/2,cy+yy*gy-sz/2,sz,sz)}ctx.strokeStyle='#66f272';ctx.lineWidth=2*u;ctx.strokeRect(cx-40*u,cy-31*u,80*u,62*u)}
function cameraLandscapeUI(w,h,u,p){var r=viewRect();ctx.fillStyle='#fff';ctx.font='600 '+(12*u)+'px monospace';ctx.textAlign='left';ctx.fillText('M   RAW  L',14*u,r.y/2);ctx.textAlign='right';ctx.fillText('AF-S   ▰ 87%',w-14*u,r.y/2);cameraPoints(r,u,p);ctx.font='700 '+(15*u)+'px monospace';ctx.textAlign='left';ctx.fillText(q('#mc-shutter').value,18*u,h-34*u);ctx.fillText('F'+q('#mc-aperture').value,w*.24,h-34*u);ctx.fillText('±0.0',w*.41,h-34*u);ctx.fillText('ISO '+q('#mc-iso').value,w*.58,h-34*u);ctx.textAlign='right';ctx.fillText('999',w-18*u,h-34*u)}
function cameraPortraitUI(w,h,u,p){var r=viewRect(),s=w/520;ctx.fillStyle='#fff';ctx.font='600 '+(12*s)+'px monospace';ctx.textAlign='left';ctx.fillText('M  RAW',14*s,r.y/2);ctx.textAlign='right';ctx.fillText('AF-S  ▰',w-14*s,r.y/2);cameraPoints(r,s,p);ctx.font='700 '+(13*s)+'px monospace';ctx.textAlign='left';ctx.fillText(q('#mc-shutter').value,16*s,h-62*s);ctx.fillText('F'+q('#mc-aperture').value,w*.27,h-62*s);ctx.fillText('ISO '+q('#mc-iso').value,w*.53,h-62*s);ctx.textAlign='right';ctx.fillText('[999]',w-16*s,h-62*s);ctx.strokeStyle='#fff';ctx.beginPath();ctx.moveTo(w*.22,h-32*s);ctx.lineTo(w*.78,h-32*s);ctx.stroke();ctx.fillStyle='#66f272';ctx.beginPath();ctx.arc(w/2,h-32*s,4*s,0,Math.PI*2);ctx.fill()}
function filmTexture(w,h,u,portrait){var tone=q('#mc-film-tone').value,warm=ctx.createLinearGradient(0,0,w,h);if(tone==='warm'){warm.addColorStop(0,'rgba(245,164,98,.16)');warm.addColorStop(1,'rgba(83,45,26,.08)')}else if(tone==='cool'){warm.addColorStop(0,'rgba(105,164,224,.13)');warm.addColorStop(1,'rgba(24,52,91,.16)')}else{warm.addColorStop(0,'rgba(220,210,190,.06)');warm.addColorStop(1,'rgba(30,38,48,.06)')}ctx.fillStyle=warm;ctx.fillRect(0,0,w,h);var lx=portrait?w*.12:-w*.04,leak=ctx.createRadialGradient(lx,h*.24,0,lx,h*.24,portrait?w*.55:w*.32);leak.addColorStop(0,tone==='cool'?'rgba(76,142,255,.16)':'rgba(255,91,38,.22)');leak.addColorStop(1,'rgba(255,91,38,0)');ctx.fillStyle=leak;ctx.fillRect(0,0,w,h);var grain=q('#mc-film-grain').value,mult=grain==='low'?.5:grain==='high'?1.7:1;ctx.globalAlpha=grain==='low'?.07:grain==='high'?.18:.12;var count=Math.round((portrait?230:190)*mult);for(var i=0;i<count;i++){ctx.fillStyle=i%4?'#fff':'#000';ctx.fillRect((i*97)%w,(i*53)%h,Math.max(1,u),Math.max(1,u))}ctx.globalAlpha=1}
function filmLandscapeUI(w,h,u){filmTexture(w,h,u,false);filmDate(w,h,u,17*u,18*u)}function filmPortraitUI(w,h,u){var s=w/520;filmTexture(w,h,s,true);filmDate(w,h,s,18*s,24*s)}
function filmDate(w,h,s,right,bottom){if(!q('#mc-film-date').checked)return;ctx.fillStyle='#ef9b58';ctx.font='700 '+(12*s)+'px monospace';ctx.textAlign='right';var d=new Date(),stamp=d.getFullYear()+'.'+String(d.getMonth()+1).padStart(2,'0')+'.'+String(d.getDate()).padStart(2,'0');ctx.fillText(stamp,w-right,h-bottom)}
function captureEffect(p,w,h,u){if(p<.78)return;var r=viewRect();ctx.save();if(state.style==='phone'){if(p<.93){ctx.fillStyle='rgba(255,255,255,'+Math.sin((p-.78)/.15*Math.PI)*.92+')';ctx.fillRect(r.x,r.y,r.w,r.h)}if(p>=.93){var s=Math.min(w,h)/405,tw=44*s,th=44*s,tx=state.orientation==='portrait'?18*s:w-70*s,ty=state.orientation==='portrait'?h-70*s:h-62*s;ctx.save();ctx.beginPath();ctx.rect(tx,ty,tw,th);ctx.clip();var sc=Math.max(tw/state.img.width,th/state.img.height),sw=tw/sc,sh=th/sc;ctx.drawImage(state.img,(state.img.width-sw)/2,(state.img.height-sh)/2,sw,sh,tx,ty,tw,th);ctx.restore();ctx.strokeStyle='#fff';ctx.lineWidth=2*s;ctx.strokeRect(tx,ty,tw,th)}}else if(state.style==='camera'){if(p<.91){var a=Math.sin((p-.78)/.13*Math.PI);ctx.fillStyle='rgba(0,0,0,'+Math.max(0,a*.96)+')';ctx.fillRect(r.x,r.y,r.w,r.h)}if(p>=.91){ctx.fillStyle='#69f27a';ctx.beginPath();ctx.arc(w-28*u,18*u,4*u,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='600 '+(10*u)+'px monospace';ctx.textAlign='right';ctx.fillText('CARD',w-38*u,18*u)}}else{var b=Math.max(0,1-Math.abs(p-.87)/.1),burn=ctx.createRadialGradient(w*.18,h*.45,0,w*.18,h*.45,w*.8);burn.addColorStop(0,'rgba(255,246,202,'+b*.72+')');burn.addColorStop(.45,'rgba(255,116,35,'+b*.38+')');burn.addColorStop(1,'rgba(80,8,0,0)');ctx.fillStyle=burn;ctx.fillRect(0,0,w,h)}ctx.restore()}
function draw(progress,pan){if(!state.img)return;setup();var r=viewRect();ctx.fillStyle=state.style==='film'?'#17120f':'#000';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.save();ctx.beginPath();ctx.rect(r.x,r.y,r.w,r.h);ctx.clip();ctx.filter='blur('+Math.max(0,(1-progress)*12)+'px) saturate('+(.72+progress*.28)+')';cover(state.img,1.08-progress*.05,pan||0,r);ctx.restore();overlay(progress)}
function toast(msg){var el=q('#mc-toast');el.textContent=msg;el.style.display='block';setTimeout(function(){el.style.display='none'},2200)}
function ready(){draw(1,0);q('#mc-play').disabled=q('#mc-png').disabled=q('#mc-gif').disabled=false}
function loadImage(blob){if(!blob||!blob.type.match(/^image\//)){toast(t('bad'));return}toast(t('loading'));var url=URL.createObjectURL(blob),img=new Image();img.onload=function(){var max=2400,scale=Math.min(1,max/Math.max(img.width,img.height));if(scale<1){var c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);var reduced=new Image();reduced.onload=function(){state.img=reduced;ready()};reduced.src=c.toDataURL('image/jpeg',.9)}else{state.img=img;ready()}URL.revokeObjectURL(url)};img.onerror=function(){toast(t('bad'));URL.revokeObjectURL(url)};img.src=url}
file.addEventListener('change',function(){loadImage(file.files[0])});['dragenter','dragover'].forEach(function(n){drop.addEventListener(n,function(e){e.preventDefault();drop.classList.add('drag')})});['dragleave','drop'].forEach(function(n){drop.addEventListener(n,function(e){e.preventDefault();drop.classList.remove('drag')})});drop.addEventListener('drop',function(e){loadImage(e.dataTransfer.files[0])});document.addEventListener('paste',function(e){if(root.isConnected&&e.clipboardData&&e.clipboardData.files[0])loadImage(e.clipboardData.files[0])});
function animate(){if(!state.img||state.playing)return;state.playing=true;var start=performance.now(),duration=3600;function frame(now){var p=Math.min(1,(now-start)/duration);draw(Math.min(1,p*1.35),Math.sin(p*Math.PI*2)*.45);if(p<1)requestAnimationFrame(frame);else{state.playing=false;q('#mc-play').textContent=t('replay')}}requestAnimationFrame(frame)}q('#mc-play').addEventListener('click',animate);
function download(blob,name){var a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(u)},1000);toast(t('done'))}
q('#mc-png').addEventListener('click',function(){draw(1,0);canvas.toBlob(function(b){download(b,'memory-camera.png')},'image/png')});
q('#mc-gif').addEventListener('click',function(){if(!window.GIF||!state.img)return;var btn=this,box=q('#mc-progress'),bar=q('#mc-progress-bar'),label=q('#mc-progress-text');btn.disabled=true;box.style.display='block';label.textContent=t('encoding');var gif=new GIF({workers:2,quality:12,workerScript:'/js/vendor/gif.worker.js',width:canvas.width,height:canvas.height,repeat:q('#mc-loop').checked?0:-1});for(var i=0;i<32;i++){var p=i/31;draw(Math.min(1,p*1.35),Math.sin(p*Math.PI*2)*.45);gif.addFrame(canvas,{copy:true,delay:110})}gif.on('progress',function(p){bar.style.width=Math.round(p*100)+'%'});gif.on('finished',function(blob){download(blob,'memory-camera.gif');btn.disabled=false;box.style.display='none';bar.style.width='0'});gif.render()});
q('#mc-caption').addEventListener('input',function(){if(state.img)draw(1,0)});root.querySelectorAll('.mc-caption-controls select,.mc-caption-controls input').forEach(function(el){['input','change'].forEach(function(ev){el.addEventListener(ev,function(){if(el.id==='mc-custom-color'){state.color='custom';root.querySelectorAll('#mc-colors button').forEach(function(b){b.classList.remove('active')})}if(el.id==='mc-font-size')q('#mc-font-size-value').textContent=el.value;if(el.id==='mc-caption-y')q('#mc-caption-y-value').textContent=el.value+'%';if(state.img)draw(1,0)})})});root.querySelectorAll('.mc-params select,.mc-params input').forEach(function(el){['input','change'].forEach(function(ev){el.addEventListener(ev,function(){if(state.img)draw(1,0)})})});root.querySelectorAll('.mc-image-adjust input').forEach(function(el){el.addEventListener('input',function(){var out=q('#'+el.id+'-value');out.textContent=el.id==='mc-image-scale'?el.value+'%':el.value;if(state.img)draw(1,0)})});updateParamPanel();translate();
})();
