(function(){
'use strict';
var root=document.getElementById('omikuji-app');if(!root||root.dataset.ready)return;root.dataset.ready='1';
var data=window.OMIKUJI_DATA||[],lang='ja',current=null,step='shake',sound=true,shaking=false,last=null,total=0,finished=false,awaitingPull=false,pulling=false,pullStart=0,pullDistance=0;
var $=function(s){return root.querySelector(s)},$$=function(s){return Array.prototype.slice.call(root.querySelectorAll(s))};
var words={
ja:{kannon:'観音百籤',title:'御神籤',calm:'心を静め、願い事を思い浮かべてください。',shakeHelp:'籤筒を押さえたまま、ゆっくり振ってください。',pullHelp:'露出した籤を上へ引き抜いてください。',drawn:'一本の籤が出ました。',findDrawer:'同じ番号の引き出しを探す',yourNumber:'引いた番号',cabinetHelp:'同じ番号の引き出しを自分で探してください。',wrong:'番号が違うようです。',takePaper:'引き出しの中の御神籤を取ってください。',unfolding:'静かに御神籤を開いています……',sensoji:'浅草観音籤',original:'原文',reading:'読み解き',reflection:'吉凶だけでなく、今の自分への戒めとして静かにお読みください。',tie:'御神籤を結ぶ',keep:'持ち帰る',again:'もう一度引く',rack:'御神籤掛け',rackNote:'ここに結んだ御神籤は、このブラウザに残ります。',history:'これまでの御神籤',localOnly:'記録は現在のブラウザだけに保存されます。',clear:'すべて消去',delete:'削除',empty:'まだ記録はありません。',saved:'御神籤を持ち帰りました。',tied:'御神籤を結びました。',sourceNote:'番号・吉凶・漢詩は公開されている浅草観音百籤資料を照合。解説は本ページ独自の読解補助です。',labels:['願望','健康','失物','旅立ち','縁・恋','学び']},
zh:{kannon:'观音百签',title:'御神籤',calm:'静下心来，在心中想好想询问的事情。',shakeHelp:'按住签筒，缓缓来回摇动。',pullHelp:'请按住露出的签，向上抽出。',drawn:'一根签棒落了出来。',findDrawer:'寻找相同番号的抽屉',yourNumber:'抽签结果',cabinetHelp:'请自己寻找与签棒相同番号的抽屉。',wrong:'好像不是这个番号。',takePaper:'请取出抽屉里的御神籤。',unfolding:'正在静静展开御神籤……',sensoji:'浅草观音签',original:'传统原文',reading:'解籤',reflection:'请不要只看吉凶，也把签文当作对当下自己的提醒，静心阅读。',tie:'系上御神籤',keep:'带回去',again:'再抽一次',rack:'御神籤架',rackNote:'系在这里的御神籤会保存在当前浏览器中。',history:'我的御神籤',localOnly:'记录仅保存在当前浏览器中。',clear:'清除全部',delete:'删除',empty:'还没有保存过御神籤。',saved:'已经将御神籤带回。',tied:'已经将御神籤系好。',sourceNote:'番号、吉凶与汉诗参考公开的浅草观音百签资料交叉核对；现代解读为本站自行撰写的阅读辅助。',labels:['愿望','健康','失物','出行','缘分·恋爱','学习']},
en:{kannon:'Kannon One Hundred Lots',title:'Omikuji',calm:'Calm your mind and think of what you wish to ask.',shakeHelp:'Hold the wooden cylinder and move it gently back and forth.',pullHelp:'Hold the exposed stick and pull it upward.',drawn:'A single fortune stick has fallen out.',findDrawer:'Find the matching drawer',yourNumber:'Your number',cabinetHelp:'Find the drawer bearing the same number yourself.',wrong:"This doesn't seem to be the right number.",takePaper:'Take the folded omikuji from the drawer.',unfolding:'The omikuji is quietly unfolding…',sensoji:'Asakusa Kannon Lot',original:'Original verse',reading:'Interpretation',reflection:'Read this quietly as guidance for the present, rather than judging it only by fortune rank.',tie:'Tie the omikuji',keep:'Take it home',again:'Draw again',rack:'Omikuji rack',rackNote:'Fortunes tied here remain in this browser.',history:'My Omikuji',localOnly:'Records are stored only in this browser.',clear:'Clear all',delete:'Delete',empty:'No saved omikuji yet.',saved:'You took this omikuji home.',tied:'You tied this omikuji to the rack.',sourceNote:'Numbers, ranks, and classical verses were cross-checked against public Asakusa Kannon lot references. Modern reading aids are original to this page.',labels:['Wish','Health','Lost item','Travel','Love & bonds','Study']}}
;
var readings={
'大吉':{ja:'視界が開け、積み重ねてきたことが形になりやすい時です。勢いだけに頼らず、正しい姿勢と周囲への感謝を保つほど、よい流れが長く続くでしょう。',zh:'眼前的道路正在展开，过去的积累较容易结出成果。不要只依赖一时的顺利；守住正道并感谢身边的人，好的势头才会延续。',en:'The way ahead is opening and past effort can now take form. Do not rely on momentum alone; integrity and gratitude will help this favorable current endure.'},
'吉':{ja:'物事はおおむね穏やかに整います。急いで答えを決めるより、今ある縁と小さな前進を大切にすると、望む方向へ近づけるでしょう。',zh:'事情总体会逐渐安稳。与其急着得到答案，不如珍惜现有的缘分和每一步小小进展，它们会把你带向希望的方向。',en:'Matters should settle in a generally favorable way. Rather than forcing an answer, value present connections and modest progress; they will carry you toward what you seek.'},
'半吉':{ja:'明るさと慎重さが半ばする時です。うまく進む部分を育てながら、まだ見えない点には余白を残してください。確認を重ねることが助けになります。',zh:'这是希望与谨慎各占一半的阶段。继续培养进展顺利的部分，同时给尚未明朗之处留些余地，多做确认会有所帮助。',en:'Hope and caution share this moment. Nurture what is moving well, leave room around what remains unclear, and verify before committing.'},
'小吉':{ja:'大きな変化より、小さく確かな好転を示します。焦らず日々の手入れを続ければ、雲の切れ間から光が差すように状況は整っていくでしょう。',zh:'它提示的不是巨变，而是细小却可靠的好转。耐心照料日常，局面会像云层渐开一样一点点明朗。',en:'This points not to a dramatic turn but to small, dependable improvement. Tend to daily matters patiently and clarity will emerge little by little.'},
'末小吉':{ja:'結果は後から少しずつ現れます。今すぐの手応えが薄くても、丁寧な行いを止めないこと。末に小さな喜びが育つ兆しです。',zh:'结果会在后面一点点出现。即使眼下不太有实感，也不要停止认真行动；细小的喜悦会在后来慢慢成长。',en:'Results arrive gradually and somewhat later. Even if progress feels faint now, continue acting with care; a modest joy can grow in time.'},
'末吉':{ja:'初めは滞りがあっても、結末に向かって運びは整います。途中の不安で投げ出さず、無理のない歩幅を守ることが大切です。',zh:'起初也许会有阻滞，但走到后面局面会逐渐整理好。不要因途中不安而放弃，保持不过度勉强的步伐很重要。',en:'The beginning may feel obstructed, yet matters can settle toward the end. Do not abandon the path because of interim uncertainty; keep a sustainable pace.'},
'凶':{ja:'今は無理に押し通すより、立ち止まり整える時です。凶は不幸の確定ではなく、急ぎや油断を戒める言葉。誠実に備え、時機を待つことで流れは変わります。',zh:'现在更适合停下来整理，而不是勉强推进。“凶”并非宣判不幸，而是提醒你戒除急躁与疏忽；认真准备、等待时机，局面仍会改变。',en:'This is a time to pause and put things in order rather than force them through. Misfortune is not a sentence; it cautions against haste and neglect. Prepare sincerely and allow conditions to change.'}}
;
var tendency={
'大吉':['open','steady','return','go','warm','rise'],'吉':['grow','steady','later','go','warm','rise'],'半吉':['wait','care','later','care','wait','steady'],'小吉':['grow','recover','later','care','steady','grow'],'末小吉':['later','slow','wait','care','slow','steady'],'末吉':['wait','slow','later','care','wait','steady'],'凶':['wait','care','wait','wait','care','pause']};
var phrases={ja:{open:'望みは開けやすい。感謝を忘れずに。',steady:'丁寧に続ければ整う。',return:'遅れても戻る兆し。',go:'慎重なら進んでよい。',warm:'誠実な縁を大切に。',rise:'積み重ねが実を結ぶ。',grow:'小さな前進を育てる。',later:'結果を急がず待つ。',wait:'今は時機を待つ。',care:'無理をせず慎重に。',recover:'養生を続ければ上向く。',slow:'時間をかけて整える。',pause:'立ち止まり基礎を見直す。'},zh:{open:'愿望较容易展开，勿忘感恩。',steady:'认真持续，事情会逐渐安稳。',return:'虽有延迟，仍有回归的迹象。',go:'谨慎确认后可以前行。',warm:'珍惜真诚而温和的缘分。',rise:'积累会逐渐结出成果。',grow:'先培养微小而可靠的进展。',later:'不要催促结果，耐心等待。',wait:'当前宜等待合适时机。',care:'不要勉强，谨慎照料。',recover:'持续休养，状态会慢慢好转。',slow:'给事情足够时间整理。',pause:'先停一步，重新检查基础。'},en:{open:'The wish can open; remember gratitude.',steady:'Careful persistence brings order.',return:'What is delayed may still return.',go:'Proceed after checking carefully.',warm:'Treasure sincere and gentle bonds.',rise:'Accumulated effort can bear fruit.',grow:'Nurture small, reliable progress.',later:'Do not rush the result; wait.',wait:'Wait for a more fitting moment.',care:'Avoid strain and proceed carefully.',recover:'Continued care supports recovery.',slow:'Give the matter time to settle.',pause:'Pause and review the foundations.'}};
function t(k){return words[lang][k]||k}function numeral(n){var d=lang==='zh'?['零','一','二','三','四','五','六','七','八','九']:['〇','一','二','三','四','五','六','七','八','九'];if(lang==='en')return String(n);if(n===100)return'百';if(n<10)return d[n];if(n<20)return'十'+(n%10?d[n%10]:'');return d[Math.floor(n/10)]+'十'+(n%10?d[n%10]:'')}
function numberLabel(n){return lang==='en'?'No. '+n:(lang==='zh'?'第'+numeral(n)+'番':'第'+numeral(n)+'番')}function fortuneLabel(f){if(lang==='en')return{'大吉':'Great Fortune','吉':'Good Fortune','半吉':'Half Fortune','小吉':'Small Fortune','末小吉':'Future Small Fortune','末吉':'Future Fortune','凶':'Misfortune'}[f];return f}
function translate(){$$('[data-t]').forEach(function(el){el.textContent=t(el.dataset.t)});if(current){$('#omk-stick-number').textContent=numeral(current.number);$('#omk-number-label').textContent=numberLabel(current.number);$('#omk-target-number').textContent=numberLabel(current.number);$('#omk-drawer-number').textContent=numeral(current.number);if(step==='result')renderResult()}renderCabinet();renderHistory()}
function setStep(name,index){step=name;root.dataset.step=name;$$('[data-scene]').forEach(function(x){x.classList.toggle('active',x.dataset.scene===name)});$$('.omk-progress i').forEach(function(x,i){x.classList.toggle('active',i<=index)});if(root.getBoundingClientRect().top<0)root.scrollIntoView({behavior:'smooth',block:'start'})}
var audio=null;function ac(){if(!sound)return null;if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();return audio}function tone(freq,dur,type,vol){var a=ac();if(!a)return;var o=a.createOscillator(),g=a.createGain();o.type=type||'sine';o.frequency.value=freq;g.gain.setValueAtTime(vol||.025,a.currentTime);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+dur);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+dur)}function rattle(){tone(430,.06,'triangle',.018);setTimeout(function(){tone(310,.05,'triangle',.014)},45)}
function randomNumber(){var a=new Uint32Array(1);if(window.crypto)crypto.getRandomValues(a);else a[0]=Math.random()*4294967295;return a[0]%100+1}
var cyl=$('#omk-cylinder');function begin(e){if(finished)return;shaking=true;last={x:e.clientX||0,y:e.clientY||0};cyl.classList.add('shaking');cyl.setPointerCapture&&e.pointerId!==undefined&&cyl.setPointerCapture(e.pointerId);ac()}function move(e){if(!shaking||finished)return;var p={x:e.clientX||0,y:e.clientY||0},dist=Math.hypot(p.x-last.x,p.y-last.y);if(dist>2){total+=Math.min(dist,38);last=p;$('#omk-meter').style.width=Math.min(100,total/5.2)+'%';if(total%65<dist)rattle();if(total>=520)completeShake()}}function end(){shaking=false;cyl.classList.remove('shaking')}
function completeShake(){if(finished)return;finished=true;end();var n=randomNumber();current=data[n-1];awaitingPull=true;pullDistance=0;root.classList.add('awaiting-pull');tone(190,.16,'triangle',.035);$('#omk-stick').classList.add('drawn')}
var drawnStick=$('#omk-stick');function pullBegin(e){if(!awaitingPull)return;pulling=true;pullStart=e.clientY||0;pullDistance=0;drawnStick.classList.add('pulling');drawnStick.setPointerCapture&&e.pointerId!==undefined&&drawnStick.setPointerCapture(e.pointerId);e.preventDefault()}function pullMove(e){if(!pulling||!awaitingPull)return;pullDistance=Math.max(0,Math.min(115,pullStart-(e.clientY||0)));drawnStick.style.setProperty('--pull',pullDistance+'px');if(pullDistance>=78)finishPull()}function pullEnd(){if(!pulling)return;pulling=false;drawnStick.classList.remove('pulling');if(awaitingPull){drawnStick.style.setProperty('--pull','0px')}}function finishPull(){if(!awaitingPull)return;awaitingPull=false;pulling=false;root.classList.remove('awaiting-pull');drawnStick.classList.remove('pulling');drawnStick.classList.add('extracted');tone(520,.12,'sine',.02);setTimeout(function(){$('#omk-stick-number').textContent=numeral(current.number);$('#omk-number-label').textContent=numberLabel(current.number);setStep('number',1)},520)}
drawnStick.addEventListener('pointerdown',pullBegin);window.addEventListener('pointermove',pullMove);window.addEventListener('pointerup',pullEnd);drawnStick.addEventListener('keydown',function(e){if(awaitingPull&&(e.key==='Enter'||e.key===' ')){e.preventDefault();finishPull()}});
cyl.addEventListener('pointerdown',begin);window.addEventListener('pointermove',move);window.addEventListener('pointerup',end);cyl.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();total+=95;$('#omk-meter').style.width=Math.min(100,total/5.2)+'%';rattle();if(total>=520)completeShake()}});
function renderCabinet(){var box=$('#omk-cabinet');if(!box)return;box.innerHTML='';for(var i=1;i<=100;i++){var b=document.createElement('button');b.className='omk-drawer';b.dataset.number=i;b.textContent=numeral(i);b.setAttribute('aria-label',numberLabel(i));box.appendChild(b)}}
$('#omk-to-cabinet').addEventListener('click',function(){$('#omk-target-number').textContent=numberLabel(current.number);renderCabinet();setStep('cabinet',2)});$('#omk-cabinet').addEventListener('click',function(e){var b=e.target.closest('.omk-drawer');if(!b)return;if(+b.dataset.number!==current.number){b.classList.remove('wrong');void b.offsetWidth;b.classList.add('wrong');$('#omk-feedback').textContent=t('wrong');tone(150,.09,'sine',.012);return}$('#omk-feedback').textContent='';b.style.transform='translateY(16px)';tone(105,.35,'sawtooth',.012);$('#omk-drawer-number').textContent=numeral(current.number);setTimeout(function(){setStep('drawer',3)},650)});
$('#omk-paper-folded').addEventListener('click',function(){tone(690,.12,'triangle',.012);setStep('unfold',4);setTimeout(function(){renderResult();setStep('result',5)},1800)});
function renderResult(){if(!current)return;$('#omk-result-number').textContent=numberLabel(current.number);$('#omk-fortune').textContent=fortuneLabel(current.fortune);$('#omk-poem').textContent=current.poem.replace(/[，,]/g,'\n');$('#omk-reading').textContent=readings[current.fortune][lang];var ks=tendency[current.fortune],labels=words[lang].labels,p=phrases[lang];$('#omk-categories').innerHTML=labels.map(function(x,i){return'<div class="omk-cat"><b>'+x+'</b><span>'+p[ks[i]]+'</span></div>'}).join('')}
function getJSON(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback}catch(e){return fallback}}function record(mode){var h=getJSON('bananakiOmikujiHistory',[]);h.unshift({number:current.number,fortune:current.fortune,date:new Date().toISOString().slice(0,10),mode:mode});localStorage.setItem('bananakiOmikujiHistory',JSON.stringify(h.slice(0,50)));if(mode==='tie'){var c=+localStorage.getItem('bananakiOmikujiTies')||0;localStorage.setItem('bananakiOmikujiTies',Math.min(80,c+1))}renderHistory();renderRack();alert(mode==='tie'?t('tied'):t('saved'))}
function renderRack(){var c=+localStorage.getItem('bananakiOmikujiTies')||0,$r=$('#omk-rack');$r.innerHTML='';for(var i=0;i<c;i++){var x=document.createElement('i');x.className='omk-tied';x.style.setProperty('--r',(-7+(i*13)%15)+'deg');$r.appendChild(x)}}function renderHistory(){var h=getJSON('bananakiOmikujiHistory',[]),box=$('#omk-history-list');if(!h.length){box.innerHTML='<p>'+t('empty')+'</p>';return}box.innerHTML=h.map(function(x){return'<div class="omk-history-row"><span>'+x.date+' · '+numberLabel(x.number)+'</span><b>'+fortuneLabel(x.fortune)+'</b></div>'}).join('')}
$('#omk-tie').addEventListener('click',function(){record('tie')});$('#omk-keep').addEventListener('click',function(){record('keep')});$('#omk-again').addEventListener('click',reset);
function reset(){current=null;total=0;finished=false;awaitingPull=false;pulling=false;pullDistance=0;root.classList.remove('awaiting-pull');$('#omk-meter').style.width='0';$('#omk-stick').classList.remove('drawn','pulling','extracted');$('#omk-stick').style.removeProperty('--pull');setStep('shake',0)}
$$('[data-lang]').forEach(function(b){b.addEventListener('click',function(){$$('[data-lang]').forEach(function(x){x.classList.remove('active')});b.classList.add('active');lang=b.dataset.lang;translate()})});$('#omk-sound').addEventListener('click',function(){sound=!sound;this.textContent=sound?'🔊':'🔇';if(sound)tone(520,.08,'sine',.018)});
renderCabinet();renderRack();renderHistory();translate();
})();
